### ISSUE TITLE
Better support for grunt-fontello and LESS files

### ISSUE THREAD

**Issue by wgasowski** [jubalm/grunt-fontello#17]
It would be nice if grunt-fontello would work properly. Unfortunately current version 0.1.3 doesn't work for me. It downloads only some files using my config.json.

There is also no LESS support. It would be very useful.

**Comment by ericcornelissen** [comment]
> It would be nice if grunt-fontello would work properly. Unfortunately current version 0.1.3 doesn't work for me. It downloads only some files using my config.json.

I hope stuff works for you since 0.3.3, otherwise (if you're still using grunt-fontello) let me know what doesn't work in more detail 👍 


> There is also no LESS support. It would be very useful.

Although LESS [allows](http://lesscss.org/features/#features-overview-feature-importing) you to import .css files, I will try to add support for it 🙂

Thanks for the suggestion!
