### ISSUE TITLE
Outdated needle

### ISSUE THREAD

**Issue by rmckeel** [jubalm/grunt-fontello#25]
Hey @jubalm,

  As a related issue, package.json uses 'needle', which in its old version uses an old version of 'qs'.  This causes this error:

```
Insight-0 Grunt :: .../node_modules/grunt-fontello/node_modules/needle/node_modules/qs/lib/index.js:5
Insight-0 const Stringify = require('./stringify');
Insight-0 ^^^^^
```

Because strict mode can't use `const`.

I think updating package.json's use of needle to the latest ~0.11.0 would resolve this issue.

Thanks!

  Ryan

**Comment by rmckeel** [comment]
After making this change to update needle to version ~0.11.0, it appears the config.json file's "name" property is overwritten.  I checked back to ~0.7.0, and the same problem.  So, someone needs to review this bug (whether it be in needle or in grunt-fontello).

**Comment by rmckeel** [comment]
Looks like https://github.com/bryce-gibson/grunt-fontello fixes both of these issues.  Can you integrate bryce-gibson's pull request (and check out other PRs also?)

**Comment by titocr** [comment]
I think this isn't likely to be fixed here. I haven't looked at the other forks yet, but maybe @bryce-gibson is the most up to date.

**Comment by bryce-gibson** [comment]
That fork is working fairly well for us :-)

The initial main change was to try and avoid needing the `"name"` field in the config file; to avoid having it change all the time.

I don't think we've done anything too specific (for our needs), so it should still work the same as the main project :-)

**Comment by simison** [comment]
Perhaps @jubalm could add @bryce-gibson as a contributor to this repo? :-)

**Comment by brianhelba** [comment]
Hi all: @rmckeel @titocr @bryce-gibson @simison 

@rubensayshi just merged https://github.com/jubalm/grunt-fontello/pull/26 , which fixes the issue with needle / qs. The biggest challenge now is to get it released.

I share everyone's concerns about making sure this project has an active maintainer. Has the fork over on @bryce-gibson been published anywhere (NPM, etc.?). If it turns out forking is necessary, we should all try to consolidate around one. There's no reason for the codebase to fragment just because the original author is gone.

**Comment by jubalm** [comment]
Hi guys, apologies for the seemingly dead nature of this project. I have added @rubensayshi as npm publisher and @brianhelba as collaborator here because I can't find his handle in npm

**Comment by rmckeel** [comment]
Thank you @jubalm, @bryce-gibson for your activity on this and addressing the issues!
